[package]
name = "qser"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []

[dependencies]
qser-derive = { path = "./derive" }

[workspace]
resolver = "3"
members = [ ".", "derive" ]
